# Étape 1 : Construction de l'application Angular
FROM node:18 AS build

# Définir le répertoire de travail
WORKDIR /app

# Copier les fichiers package.json et package-lock.json pour installer les dépendances
COPY package*.json ./ 

# Configurer le cache npm dans le dossier /app/.npm-cache
RUN npm config set cache /app/.npm-cache --global

# Mettre à jour npm et installer Angular CLI globalement
RUN npm install -g npm@10.9.0 && \
    npm install -g @angular/cli@16.1.4 && \
    npm install --legacy-peer-deps --fetch-timeout=120000 --network-timeout=120000

# Copier tous les fichiers sources de l'application
COPY . .

# Construire l'application Angular pour la production
RUN ng build --configuration production

# Étape 2 : Créer l'image finale avec Nginx pour servir l'application
FROM nginx:alpine

# Copier les fichiers générés par la construction de l'application Angular
COPY --from=build /app/dist/skote/ /usr/share/nginx/html


# Exposer le port 80 pour Nginx
EXPOSE 80

# Démarrer Nginx
CMD ["nginx", "-g", "daemon off;"]
