services:
  mysql:
    image: mysql:8.0.33
    restart: unless-stopped
    container_name: mysql_db  
    environment:
      MYSQL_ROOT_PASSWORD: "samar123*/"  
      MYSQL_DATABASE: databaseBank
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    depends_on:
      - mysql
    restart: on-failure
    container_name: atlaslabs-backend  
    ports:
      - "8083:8083"
    environment:
      SPRING_APPLICATION_JSON: |
        {
          "spring.datasource.url": "jdbc:mysql://mysql_db:3306/databaseBank?createDatabaseIfNotExist=true&useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&allowPublicKeyRetrieval=true",
          "spring.datasource.username": "root",
          "spring.datasource.password": "samar123*/",
          "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQLDialect",
          "spring.jpa.hibernate.ddl-auto": "update"
        }

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    restart: on-failure
    container_name: atlaslabs-frontend 
    ports:
      - "4200:80"  

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8084:8080"
      - "50000:50000" # Port pour les agents Jenkins
    volumes:
      - jenkins_home:/var/jenkins_home
    environment:
      - JENKINS_OPTS=--httpPort=8084
    restart: always

volumes:
  mysql_data:
  jenkins_home:
