services:
  mysql:
    image: mysql:8.0.33
    restart: unless-stopped
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: "samar123*/"
      MYSQL_DATABASE: databaseBank
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    depends_on:
      - mysql
    restart: on-failure
    container_name: atlaslabs-backend
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql_db:3306/databaseBank?createDatabaseIfNotExist=true&useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "samar123*/"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: "org.hibernate.dialect.MySQLDialect"
      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    restart: on-failure
    container_name: atlaslabs-frontend
    ports:
      - "4200:80"

volumes:
  mysql_data:
