version: '3.8'

services:
  # Service pour la base de données MySQL
  mysql:
    image: mysql:8.0.33
    restart: unless-stopped
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: "samar123*/"  # Entouré de guillemets pour éviter les erreurs de parsing
      MYSQL_DATABASE: databaseBank
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # Service pour le backend Spring Boot
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    depends_on:
      - mysql
    restart: on-failure
    container_name: backend_service
    ports:
      - "8083:8083"
    environment:
      SPRING_APPLICATION_JSON: |
        {
          "spring.datasource.url": "jdbc:mysql://mysql_db:3306/databaseBank?createDatabaseIfNotExist=true&useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC",
          "spring.datasource.username": "root",
          "spring.datasource.password": "samar123*/",  # Entouré de guillemets pour éviter les erreurs de parsing
          "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQLDialect",
          "spring.jpa.hibernate.ddl-auto": "update"
        }

  # Service pour le frontend Angular
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    restart: on-failure
    container_name: frontend_service
    ports:
      - "4200:80"  # Mappe le port 4200 de l'hôte au port 80 du conteneur Nginx pour Angular

volumes:
  mysql_data:
